#!/usr/bin/env bash
set -o noglob
arr=($*)
echo "regionMut mode selected ${arr[0]}"


MODE="${arr[0]}"

unset arr[0]

# join rest of the array
ARGUMENTS=""

for var in "${arr[@]}"
do
  ARGUMENTS="$ARGUMENTS ${var}"
  # do something on $var
done

echo "Arguments sent to regionmut $MODE, $ARGUMENTS"

Rscript -e "source(file = system.file(\"exec/regionMut_$MODE.R\", package = \"regionMut\"))" $ARGUMENTS
set +o noglob
